version: '3.8'

networks:
  pose-estimation-network:
    driver: bridge

volumes:
  target-kafka-data:
    driver: local
  target-data:
    driver: local
  target-output:
    driver: local
  query-kafka-data:
    driver: local
  query-data:
    driver: local
  query-output:
    driver: local
  shared-data:
    driver: local
  shared-output:
    driver: local

services:
  target-kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: target-kafka
    container_name: target-kafka
    ports:
    - 9093:9092
    networks:
    - pose-estimation-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@target-kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://target-kafka:29092,CONTROLLER://target-kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://target-kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: zKDRDeqfR-y0doLyGaLoww
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
    - target-kafka-data:/var/lib/kafka/data
    user: 0:0
    healthcheck:
      test: kafka-topics --bootstrap-server target-kafka:29092 --list
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  target-api:
    build: ./target-pipeline/target-api
    container_name: target-api
    networks:
    - pose-estimation-network
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=target-kafka:29092
    - CUDA_VISIBLE_DEVICES=0
    volumes:
    - target-data:/app/data
    - target-output:/app/output
    - shared-data:/app/shared
    depends_on:
      target-kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  query-kafka:
    image: confluentinc/cp-kafka:latest
    hostname: query-kafka
    container_name: query-kafka
    ports:
    - 9092:9092
    networks:
    - pose-estimation-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@query-kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://query-kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
    - query-kafka-data:/tmp/kraft-combined-logs
    user: 0:0
    healthcheck:
      test: [
        "CMD-SHELL",
        "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"
      ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  query-api:
    build: ./query-pipeline/query-api
    container_name: query-api
    networks:
    - pose-estimation-network
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=query-kafka:9092
    - CUDA_VISIBLE_DEVICES=0
    volumes:
    - query-data:/app/data
    - query-output:/app/output
    - shared-data:/app/shared
    depends_on:
      query-kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7861/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  pose-overlay-pipeline:
    build: ./pose-overlay-pipeline
    container_name: pose-overlay-pipeline
    networks:
    - pose-estimation-network
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=target-kafka:29092,query-kafka:9092
    - OMP_NUM_THREADS=16
    - OPENBLAS_NUM_THREADS=16
    - CUDA_VISIBLE_DEVICES=0
    volumes:
    - shared-data:/app/data
    - shared-output:/app/output
    - target-output:/app/target_data
    - query-output:/app/query_data
    depends_on:
      target-kafka:
        condition: service_healthy
      query-kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
    - 3000:3000
    networks:
    - pose-estimation-network
    depends_on:
      target-api:
        condition: service_healthy
      query-api:
        condition: service_healthy
      pose-overlay-pipeline:
        condition: service_healthy
    environment:
    - NODE_ENV=production
    - API_TARGET_URL=http://target-api:8001
    - API_QUERY_URL=http://query-api:7861
    - API_POSE_URL=http://pose-overlay-pipeline:8002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
